// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0Mu7yEli9Ir2FfLNAZAkx8NhMN95xxSA',
    appId: '1:82814776396:web:72b689a1165ccdc4fd70e9',
    messagingSenderId: '82814776396',
    projectId: 'food-track-5cd0d',
    authDomain: 'food-track-5cd0d.firebaseapp.com',
    storageBucket: 'food-track-5cd0d.firebasestorage.app',
    measurementId: 'G-ZZRSLHBRG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs8XV_qNFkBSxzQVrUSXmu0r94vEM-gIs',
    appId: '1:82814776396:android:d7658bc50fe28429fd70e9',
    messagingSenderId: '82814776396',
    projectId: 'food-track-5cd0d',
    storageBucket: 'food-track-5cd0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS_ECzBrl96geQCYeHMJbwmOVN6RSlGFI',
    appId: '1:82814776396:ios:f8b1a645d95c7481fd70e9',
    messagingSenderId: '82814776396',
    projectId: 'food-track-5cd0d',
    storageBucket: 'food-track-5cd0d.firebasestorage.app',
    iosBundleId: 'com.example.foodTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS_ECzBrl96geQCYeHMJbwmOVN6RSlGFI',
    appId: '1:82814776396:ios:f8b1a645d95c7481fd70e9',
    messagingSenderId: '82814776396',
    projectId: 'food-track-5cd0d',
    storageBucket: 'food-track-5cd0d.firebasestorage.app',
    iosBundleId: 'com.example.foodTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0Mu7yEli9Ir2FfLNAZAkx8NhMN95xxSA',
    appId: '1:82814776396:web:afbce26a6d47903efd70e9',
    messagingSenderId: '82814776396',
    projectId: 'food-track-5cd0d',
    authDomain: 'food-track-5cd0d.firebaseapp.com',
    storageBucket: 'food-track-5cd0d.firebasestorage.app',
    measurementId: 'G-XTL7T916S9',
  );
}
